package entity;
// Generated Mar 31, 2018 4:31:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private String bookingId;
     private Customer customer;
     private User user;
     private Date bookingDate;
     private String shift;
     private String description;
     private BookingDetail bookingDetail;

    public Booking() {
    }

	
    public Booking(String bookingId, Customer customer, User user) {
        this.bookingId = bookingId;
        this.customer = customer;
        this.user = user;
    }
    public Booking(String bookingId, Customer customer, User user, Date bookingDate, String shift, String description, BookingDetail bookingDetail) {
       this.bookingId = bookingId;
       this.customer = customer;
       this.user = user;
       this.bookingDate = bookingDate;
       this.shift = shift;
       this.description = description;
       this.bookingDetail = bookingDetail;
    }
   
    public String getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(Date bookingDate) {
        this.bookingDate = bookingDate;
    }
    public String getShift() {
        return this.shift;
    }
    
    public void setShift(String shift) {
        this.shift = shift;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BookingDetail getBookingDetail() {
        return this.bookingDetail;
    }
    
    public void setBookingDetail(BookingDetail bookingDetail) {
        this.bookingDetail = bookingDetail;
    }




}


