package entity;
// Generated Mar 31, 2018 4:31:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private String categoryId;
     private String categoryName;
     private String description;
     private Set rooms = new HashSet(0);

    public Category() {
    }

	
    public Category(String categoryId) {
        this.categoryId = categoryId;
    }
    public Category(String categoryId, String categoryName, String description, Set rooms) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.description = description;
       this.rooms = rooms;
    }
   
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Set rooms) {
        this.rooms = rooms;
    }




}


