package entity;
// Generated Mar 31, 2018 4:31:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private String menuId;
     private String menuName;
     private String price;
     private String titleMenu;
     private String description;
     private Boolean status;
     private Set bookingDetails = new HashSet(0);

    public Menu() {
    }

	
    public Menu(String menuId) {
        this.menuId = menuId;
    }
    public Menu(String menuId, String menuName, String price, String titleMenu, String description, Boolean status, Set bookingDetails) {
       this.menuId = menuId;
       this.menuName = menuName;
       this.price = price;
       this.titleMenu = titleMenu;
       this.description = description;
       this.status = status;
       this.bookingDetails = bookingDetails;
    }
   
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getTitleMenu() {
        return this.titleMenu;
    }
    
    public void setTitleMenu(String titleMenu) {
        this.titleMenu = titleMenu;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getBookingDetails() {
        return this.bookingDetails;
    }
    
    public void setBookingDetails(Set bookingDetails) {
        this.bookingDetails = bookingDetails;
    }




}


