package entity;
// Generated Mar 31, 2018 4:31:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service  implements java.io.Serializable {


     private String serviceId;
     private String serviceName;
     private String price;
     private String description;
     private Boolean status;
     private Set bookingDetails = new HashSet(0);

    public Service() {
    }

	
    public Service(String serviceId) {
        this.serviceId = serviceId;
    }
    public Service(String serviceId, String serviceName, String price, String description, Boolean status, Set bookingDetails) {
       this.serviceId = serviceId;
       this.serviceName = serviceName;
       this.price = price;
       this.description = description;
       this.status = status;
       this.bookingDetails = bookingDetails;
    }
   
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getBookingDetails() {
        return this.bookingDetails;
    }
    
    public void setBookingDetails(Set bookingDetails) {
        this.bookingDetails = bookingDetails;
    }




}


